version: '3.7'
services:

  thelounge:
    build:
      context: ./
    ports:
      - 9000:9000
      - 144.76.199.164:113:9001
    restart: always
    volumes:
      - .thelounge/config.js:/thelounge/defaults/config.js # bind lounge config from the host's file system
      - ./custom/public/img:/thelounge/public/img
      - ./custom/public/themes:/thelounge/public/themes
      - ./custom/public/favicon.ico:/thelounge/public/favicon.ico
    networks:
      - nginx
      
networks:
  nginx:
    external: true